name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        uses: engineerd/setup-minikube@v1

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build Docker image
        run: docker build -t test-GHA .

      - name: Load Docker image into Minikube
        run: |
          eval $(minikube docker-env)
          docker tag my-image:latest my-image:minikube
          kubectl apply -f kubernetes.yaml

      - name: Wait for deployment
        run: kubectl rollout status deployment/my-app
